name: eslint
on: [push, pull_request]
jobs:
  run-eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: "npm"
      - run: npm ci --ignore-scripts
      - if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: npm-log
          path: /home/runner/.npm/_logs/
      - run: npx eslint .
